dbURL = "host=127.0.0.1 port=5432 user=lvcong dbname=ebook password=password sslmode=disable"
addr = ":8002"
secret_key = "f3efef74-c99f-4224-9491-2f347d5318b5"
mode = "debug"
verify_user_url = "http://localhost:8001/api/v1/verify_auth_token"
user_server_timeout = 5
dest_path = "/tmp/books"
default_cover_img = "static/img/default.jpeg"
book_search_index_file = "/tmp/books.bleve"
per_page_item = 20